name: Build

on:
  pull_request:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/build.yml'
  push:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/build.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - "1.90.0" # MSRV
          - stable
        os-arch:
          - ubuntu-24.04-x86_64
          - ubuntu-24.04-aarch64
        include:
          - os-arch: ubuntu-24.04-x86_64
            runner: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os-arch: ubuntu-24.04-aarch64
            runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
      - run: cargo build --workspace --all-targets --all-features --target ${{ matrix.target }}
